spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: postgres15
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

security:
  jwt:
    secret: aGZqa2hrampuamh1d3Vqa2Nja2Fjamtrbm1KS0RIRFNTTEtMS0xES0RTS0tES0ZLTlNQSUVPOTlJSkRL
    access: 3600000
    refresh: 2592000000
springdoc:
  override-with-generic-response: false